runtime: nodejs20
service: frontend-197
instance_class: F1

handlers:
  # Serve static assets (js, css, images, fonts, dll)
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|woff2?|ttf|eot|map))$
    static_files: build/\1
    upload: build/.*\.(js|css|png|jpg|jpeg|gif|svg|ico|json|woff2?|ttf|eot|map)$

  # Fallback all other URLs to index.html (for React Router)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

default_expiration: "1h"
