steps:
  # Install dependencies dengan caching npm agar build lebih cepat
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Build React app
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "app",
        "deploy",
        "app.yaml",
        "--quiet",
        "--project=YOUR_PROJECT_ID"  # opsional: ganti sesuai project ID kamu
      ]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"  # opsional, perpanjang timeout kalau build lama
