### 📌 REGISTER Admin (tabel admin)
POST https://notes-backend197-174534490336.us-central1.run.app/api/auth/register
Content-Type: application/json

{
  "username": "admin32",
  "password": "admin123"
}

###

### 🔐 LOGIN Admin (untuk mendapatkan token)
POST https://notes-backend197-174534490336.us-central1.run.app/api/auth/login
Content-Type: application/json

{
  "username": "admin32",
  "password": "admin123"
}

###

### 🔑 GANTI TOKEN DI SINI SETELAH LOGIN
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiaWF0IjoxNzQ4MjYxMDQ3LCJleHAiOjE3NDgzNDc0NDd9.oxxyRWPrJWhyqFCALgQywOCjD71C8rNgdPf1nNc4ycI

###

### 📥 GET Semua Catatan
GET https://notes-backend197-174534490336.us-central1.run.app/api/users
Authorization: Bearer {{token}}
###

### 🔍 GET Catatan by ID
GET https://notes-backend197-174534490336.us-central1.run.app/api/users/14
Authorization: Bearer {{token}}
###

### ➕ POST Catatan Baru
POST https://notes-backend197-174534490336.us-central1.run.app/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Hari yang berat",
  "content": "Hari ini banyak tugas kuliah menumpuk dan butuh istirahat."
}

###

### ✏️ PATCH / Update Catatan dengan ID=15
PATCH https://notes-backend197-174534490336.us-central1.run.app/api/users/15
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Hari yang cukup tenang",
  "content": "Setelah menyelesaikan tugas, saya bisa istirahat dengan tenang."
}

###

### ❌ DELETE Catatan dengan ID=14
DELETE https://notes-backend197-174534490336.us-central1.run.app/api/users/14
Authorization: Bearer {{token}}
